name = "my-device-control-web"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "COMMANDS"
id = "c5717f9f088e4cd9962be6a9c6cd20b4"

[[kv_namespaces]]
binding = "SYNC_DATA"
id = "e2c76194ed35478eb9155b4c1a59acc3"
